### ISSUE TITLE
ValueError: not enough values to unpack (expected 5, got 2)

### ISSUE THREAD

**Issue by zhiweihu1103** [HarryShomer/QUAD#1]
File "src/run.py", line 272, in <module>
    main()
  File "src/run.py", line 267, in main
    training_loop_gcn(**args)
  File "/work/zhiweihu/reproduce-code/new_try/QUAD-master/src/loops/loops.py", line 89, in training_loop_gcn
    obj_preds, aux_preds = model(_sub, _rel, _quals, aux_ent=aux_ent_dict)
  File "/home/hzw/.conda/envs/cole/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/zhiweihu/reproduce-code/new_try/QUAD-master/src/models/hyper_gcn.py", line 124, in forward
    s_emb, r_emb, qe_emb, qr_emb, o_emb = self.index_embs_aux(x, r, aux_ent['base_sub_ix'], aux_ent['base_rel_ix'], aux_ent['base_obj_ix'], aux_ent['quals'])
ValueError: not enough values to unpack (expected 5, got 2)

when I run the script:
python src/run.py wd50k_100 --clean-data --alpha .6 --aux-ent --aux-weight 1 \
--qual-layers 1 --encoder-drop1 .2 --encoder-drop2 .2 \
--batch-size 256 --trans-dim 768 --mask --label-smooth 0.1 \
--aux-ent-smooth 0.1 --parallel --parallel-drop .3 --device cuda:5

**Comment by HarryShomer** [comment]
Hi Zhiwei,

I'm unable to reproduce the error when running the command you provided. It runs fine for me.

I have a few questions:

1. Are you running the most recent version of the code?

**Comment by HarryShomer** [comment]
Hi Zhiwei,

I'm unable to reproduce the error when running the command you provided. It runs fine for me.

I think the issue is that you're running it with python 3.7. Can you try running it with 3.8?

You can also try adding parentheses around the return statement on line 81.
```
return (*self.index_embs(x, r, sub_ix, rel_ix, quals_ix), obj_emb)
```

Best,
Harry

**Comment by zhiweihu1103** [comment]
OK, let me check.  The other thing is about the reproduction of the paper. I used the following script to run (on the WD50K_100 dataset, I delete the --aux-ent parameter), but I only get the results of MRR=65.2, Hits@1=59.0, Hit@10=76.2, is this normal?  There is a big gap compared with the results in the article.

python src/run.py wd50k_100 --clean-data --alpha .6 --aux-weight 1
--qual-layers 1 --encoder-drop1 .2 --encoder-drop2 .2
--batch-size 256 --trans-dim 768 --mask --label-smooth 0.1
--aux-ent-smooth 0.1 --parallel --parallel-drop .3 --device cuda:5

**Comment by HarryShomer** [comment]
As noted in the paper (see section 5.3), the ablation study shown in Table 3 was run using the non-parallel setting. Removing the `--parallel --parallel-drop .3` arguments should replicate the results.

**Comment by zhiweihu1103** [comment]
My running script above should correspond to the **QUAD (Parallel)** in Table 2, right? If so, the results are quite different.

**Comment by HarryShomer** [comment]
No. By omitting the `-aux-ent` argument you are removing the auxiliary loss (i.e. setting beta=0 in Eq. 14). The results in table 2 are when beta=1. 

In Table 3 we detail the results on WD50K-100 (under the non-parallel setting) for different ablations. The row corresponding to the model without the auxiliary loss is the method titled `w/o Qual Mask`. We see that by removing it the MRR decreases to 0.677.

**Comment by zhiweihu1103** [comment]
That is, the result I get with following script. MRR=65.2, Hits@1=59.0, Hit@10=76.2, I should compare with MRR=67.7, Hits@1=61.3, Hit@10=79.4. 

python src/run.py wd50k_100 --clean-data --alpha .6 --aux-weight 1
--qual-layers 1 --encoder-drop1 .2 --encoder-drop2 .2
--batch-size 256 --trans-dim 768 --mask --label-smooth 0.1
--aux-ent-smooth 0.1 --parallel --parallel-drop .3 --device cuda:5

Because it is difficult for my own model to surpass you now, I have to ensure that your results can be reproduced, but there are always some differences between the results I run and the article, and I have not modified anything except the script parameters.

**Comment by zhiweihu1103** [comment]
Sorry, maybe the follwoing script can be used to compare with **w/o Qual Mask**. I will try.

python src/run.py wd50k_100 --clean-data --alpha .6 --aux-weight 1
--qual-layers 1 --encoder-drop1 .2 --encoder-drop2 .2
--batch-size 256 --trans-dim 768 --mask --label-smooth 0.1
--aux-ent-smooth 0.1 --device cuda:5

**Comment by zhiweihu1103** [comment]
I will close the issue, I get the nearly score with the papers, thx.

**Comment by zhiweihu1103** [comment]
Sorry, I need to ask you another question. The MRR result of the JF17K_33 data set (the one you provided) is almost 0 under the default parameters of your JF17K. However the JF17K_66  and JF17K_100 datasets are normal. I want to ask what is going on?

**Comment by HarryShomer** [comment]
The JF17K_33, JF17K_66, and jf17k_100 were old datasets that weren't used at all in the paper. No experiments were conducted on them and as such they weren't included in the paper.  

Please ignore them. I'll remove them from this repo to prevent any confusion.

**Comment by zhiweihu1103** [comment]
I have a requirement to use these three datasets, but training on JF17K_66 and JF17K_100 is normal, and MRR is always close to 0 on JF17K_33, can you give some advice?

**Comment by zhiweihu1103** [comment]
[jf17k_33.txt](https://github.com/HarryShomer/QUAD/files/9639906/jf17k_33.txt)

This is my training log. I have trained on both Hy-Transformer and StarE, and the results are all good, indicating that the data set should be fine, but I have not been able to find other reasons.

**Comment by HarryShomer** [comment]
As per my last comment they were never used nor discussed in the paper at all. 

Furthermore, while I created them I never actually ran any experiments on them. So I have no advice to offer. 

I strongly encourage you to ignore them.

**Comment by zhiweihu1103** [comment]
Ok, maybe I need to create a jf17k_33 dataset myself and try.
