### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by glasdfghjkl** [HarryShomer/QUAD#2]
Hi, thanks for the code.
I tried to run the code, but some libraries are crashing.
Could you specify the version you used to run the code?
Thanks in advance

**Comment by HarryShomer** [comment]
Hi @glasdfghjkl,

It runs fine on my end using the the specifications in the `requirements.txt`. 

Could you share the error with me?

Also fwiw, a python version of at least 3.8 is required to run the code.

Regards,
Harry

**Comment by glasdfghjkl** [comment]
It was due to my cuda version.
Thank you!
